### ISSUE TITLE
futhark-0.25.36: ambiguous occurrence of Record in Futhark.Script

### ISSUE THREAD

**Issue by sternenseemann** [diku-dk/futhark#2397]
futhark-0.25.36 fails to compile with GHC 9.10.3:

```
[231 of 331] Compiling Futhark.Script   ( src/Futhark/Script.hs, dist/build/Futhark/Script.o, dist/build/Futhark/Script.dyn_o )
src/Futhark/Script.hs:157:18: error: [GHC-87543]
    Ambiguous occurrence ‘Record’.
    It could refer to
       either ‘Futhark.Server.Record’,
              imported from ‘Futhark.Server’ at src/Futhark/Script.hs:55:1-21,
           or ‘Futhark.Script.Record’,
              defined at src/Futhark/Script.hs:122:5.
    |
157 |       pprPrec _ (Record m) = braces $ align $ commasep $ map field m
    |                  ^^^^^^

src/Futhark/Script.hs:213:25: error: [GHC-87543]
    Ambiguous occurrence ‘Record’.
    It could refer to
       either ‘Futhark.Server.Record’,
              imported from ‘Futhark.Server’ at src/Futhark/Script.hs:55:1-21,
           or ‘Futhark.Script.Record’,
              defined at src/Futhark/Script.hs:122:5.
    |
213 |           inBraces sep (Record <$> (pField `sepEndBy` pComma)),
    |                         ^^^^^^

src/Futhark/Script.hs:337:3: error: [GHC-87543]
    Ambiguous occurrence ‘Record’.
    It could refer to
       either ‘Futhark.Server.Record’,
              imported from ‘Futhark.Server’ at src/Futhark/Script.hs:55:1-21,
           or ‘Futhark.Script.Record’,
              defined at src/Futhark/Script.hs:122:5.
    |
337 |   Record $ M.toList $ M.map valueToExp fs
    |   ^^^^^^

src/Futhark/Script.hs:714:26: error: [GHC-87543]
    Ambiguous occurrence ‘Record’.
    It could refer to
       either ‘Futhark.Server.Record’,
              imported from ‘Futhark.Server’ at src/Futhark/Script.hs:55:1-21,
           or ‘Futhark.Script.Record’,
              defined at src/Futhark/Script.hs:122:5.
    |
714 |       evalExp' vtable e@(Record m) = do
    |                          ^^^^^^

src/Futhark/Script.hs:810:12: error: [GHC-87543]
    Ambiguous occurrence ‘Record’.
    It could refer to
       either ‘Futhark.Server.Record’,
              imported from ‘Futhark.Server’ at src/Futhark/Script.hs:55:1-21,
           or ‘Futhark.Script.Record’,
              defined at src/Futhark/Script.hs:122:5.
    |
810 | varsInExp (Record fs) = foldMap (foldMap varsInExp) fs
    |            ^^^^^^
```

**Comment by athas** [comment]
This is because of new exports added in `futhark-server` 1.3.1.0. I will add a revision on Hackage to require less than that version.

**Comment by athas** [comment]
I have added a revision that makes `futhark-0.25.36` require `futhark-server-1.3.0.0` specifically.

**Comment by sternenseemann** [comment]
Thanks for helping me diagnose this! Using `futhark-server == 1.3.0.0` solves the problem.

**Comment by athas** [comment]
And thanks in return for helping keep Futhark available in package managers.
