### ISSUE TITLE
Build failure with `lsp-1.5.0.0`

### ISSUE THREAD

**Issue by RyanGlScott** [diku-dk/futhark#1692]
`futhark-0.21.12` on Hackage fails to compile with `lsp-1.5.0.0`:

```
[249 of 281] Compiling Futhark.LSP.Compile ( src\Futhark\LSP\Compile.hs, dist\build\Futhark\LSP\Compile.o )

src\Futhark\LSP\Compile.hs:25:26: error:
    Module ‘Language.LSP.VFS’ does not export ‘VFS(vfsMap)’
   |
25 | import Language.LSP.VFS (VFS (vfsMap), virtualFileText)
   |                          ^^^^^^^^^^^^
```

This is most likely a consequence of haskell/lsp#404.

**Comment by athas** [comment]
I have added a Hackage revision and will fix compatibility in master soon-ish.
